clean_rooms:
  target:
    entity:
      integration: narwal_cloud
      domain: vacuum
  fields:
    rooms:
      required: true
      example: ["Kitchen", "Hallway"]
      selector:
        text:
          multiple: true
    method:
      required: false
      default: auto
      selector:
        select:
          options:
            - auto
            - start_clean
            - easy_clean
